from decouple import config

BIOSAMPLES_URL = config("BIOSAMPLES_URL", default="http://wwwdev.ebi.ac.uk")
AAP_URL = config("AAP_URL", default="https://explore.api.aai.ebi.ac.uk/auth")
AAP_USERNAME = config("AAP_USERNAME")
AAP_PASSWORD = config("AAP_PASSWORD")
DOMAIN = config("DOMAIN", default="self.BiosampleCuration")
DB_URL = config("DB_URL")
DB_USERNAME = config("DB_USERNAME")
DB_PASSWORD = config("DB_PASSWORD")
NEO4J_URL = config("NEO4J_URL", default="")
NEO4J_USERNAME = config("NEO4J_USERNAME")
NEO4J_PASSWORD = config("NEO4J_PASSWORD")

print("Reading configurations....")
print("==============================================================")
print("BIOSAMPLES_URL = " + BIOSAMPLES_URL)
print("AAP_URL = " + AAP_URL)
print("AAP_USERNAME = " + AAP_USERNAME)
print("AAP_PASSWORD = " + "XXX")
print("DOMAIN = " + DOMAIN)
print("DB_URL = " + DB_URL)
print("DB_USERNAME = " + DB_USERNAME)
print("DB_PASSWORD = " + "XXX")
print("NEO4J_URL = " + NEO4J_URL)
print("NEO4J_USERNAME = " + NEO4J_USERNAME)
print("NEO4J_PASSWORD = " + "XXX")
print("==============================================================")
