version: '3'
services:
  curami_web:
    build: .
    image: curami_web:latest
    ports:
      - 5000:5000
    depends_on:
      - neo4j
  neo4j:
    image: "neo4j:3.5.8"
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/neo5j
    volumes:
      - ./neo4j/data:/data