version: '3'
services:
  curami_web:
    build: .
    image: curami_web:latest
    ports:
      - 5000:5000
    depends_on:
      - neo4j
    links:
      - neo4j:neo4j
  neo4j:
    image: neo4j:4.1.1
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/neo5j
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
      - ./neo4j/logs:/logs
#default docker-compose network conflicts IPs with EBI intranet
#enable this if you're on Linux and you can't access internal services while docker is running
#networks:
#  default:
#    ipam:
#      config:
#      - subnet: 172.29.0.0/16

